name: Build Projeto .NET - Sem Testes

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código
        uses: actions/checkout@v3

      - name: Instalar o .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restaurar dependências
        run: dotnet restore github4women/github4women.csproj

      - name: Compilar o projeto
        run: dotnet build github4women/github4women.csproj --no-restore --configuration Release
